FROM node:18-bookworm

WORKDIR /app

COPY frontend/package.json ./
COPY frontend/yarn.lock ./

RUN yarn
RUN yarn playwright install --with-deps

COPY frontend/playwright.config.ts /app/
COPY frontend/. /app/

CMD yarn playwright test
