version: "3.8"

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: [ "redis-server", "--protected-mode", "no" ]
    volumes: 
      - cache:/data
    networks:
      - spring-staging

  postgres-db-staging:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./backend/db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=beapengine
    networks:
      - spring-staging
  
  app-staging:
    environment:
        - POSTGRESQL_URL=jdbc:postgresql://postgres-db-staging:5432/beapengine?user=root&password=root
        - PG_CRYPTO_KEY=123
    build:
      context: .
      dockerfile: Dockerfile.staging
    volumes:
      - ./services/ml-service:/usr/local/tomcat/webapps/ml-service
    ports:
      - 8080:8080
    networks:
      - spring-staging
    depends_on:
      - cache
      - postgres-db-staging
    ulimits:
      nofile:
        soft: 1000
        hard: 2000
    
  playwright:
    ports:
      - "9323:9323"
    environment:
      - CI
    build:
      context: .
      dockerfile: Dockerfile.playwright
    networks:
      - spring-staging
    depends_on:
      - app-staging
  
volumes:
  cache:

networks:
  spring-staging:
