version: "3.8"

services:
  webapp:
    container_name: webapp-dev
    image: webapp-dev
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    environment:
       - WATCHPACK_POLLING=true

  backend:
    container_name: backend-dev
    build:
      context: ./backend
    ports:
      - 8080:8080