version: "3.8"

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=123
    command: [ "redis-server", "--protected-mode", "no", "--requirepass", "123" ]
    volumes:
      - cache:/data
    networks:
      - spring

  postgres-db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./backend/db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=beapengine
      - ROLLBAR_ACCESS_TOKEN=123
    networks:
      - spring

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - spring
    depends_on:
      - postgres-db

  backend:
    container_name: backend-dev
    environment:
      - POSTGRESQL_URL=jdbc:postgresql://postgres-db:5432/beapengine?user=root&password=root
      - PG_CRYPTO_KEY=123
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - REDIS_PASSWORD=123
    build:
      context: ./backend
    volumes:
      - ./services/ml-service:/usr/local/tomcat/webapps/ml-service
    ports:
      - 8080:8080
    networks:
      - spring
    depends_on:
      - cache
      - postgres-db
    ulimits:
      nofile:
        soft: 1000
        hard: 2000

volumes:
  cache:

networks:
  spring:
