# This code processes data extracted from CSV files generated by the Python parser

rm(list = ls())

#========================Libraries=========================
list.of.packages <-
  c("Rcpp",
    "stringi",
    "lubridate",
    "xml2",
    "data.table",
    "dplyr")

new.packages <-
  list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if (length(new.packages))
  install.packages(new.packages)

library(data.table)
library(lubridate)
library(dplyr)

#=========================Variables========================
timeZone <- "America/St_Johns"
Sys.setenv(TZ = timeZone)

# Path for the output directory from the Python parser
path <- args[1]  # Main directory path
output_path <- file.path(path, "output")

#=========================Loading CSV Files========================
# Read the CSV files generated by the Python parser
heartrate <- read.csv(file.path(output_path, "heartrate.csv"))
calories <- read.csv(file.path(output_path, "calories.csv"))
steps <- read.csv(file.path(output_path, "steps.csv"))
distance <- read.csv(file.path(output_path, "distance.csv"))

#=========================Merging Data========================
# Merge all data into one dataset
output <- full_join(heartrate, calories)
output <- full_join(output, steps)
output <- full_join(output, distance)

# Sort the data by DateTime
output$DateTime <- as.POSIXct(output$DateTime, format = "%m/%d/%y %H:%M:%S")
output <- output[order(output$DateTime), ]

# Save the merged data to a new CSV file
write.csv(output,
          file.path(output_path, "fitbit_data.csv"),
          row.names = FALSE)


