name: "Code Coverage"
on:
  pull_request:

jobs:
  frontend-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          working-directory: ./frontend
          test-script: yarn test --coverage --watchAll --silent
          custom-title: Frontend Code Coverage Report
