name: "Code Coverage"
on:
  pull_request:

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Frontend code coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          working-directory: ./frontend
          test-script: yarn test
          custom-title: Frontend Code Coverage Report
      - name: Backend code coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/testCoverage/testCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Backend Code Coverage
          update-comment: true
