name: deploy-digital-ocean
on:
  # workflow_run:
  #   workflows: [frontend, playwright]
  #   branches: [master]
  #   types:
  #     - completed
  pull_request:

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: beapengine
    env:
      POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
      PG_CRYPTO_KEY: ${{ secrets.PG_CRYPTO_KEY }}
      ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build containers
        run: docker compose -f docker-compose-prod.yml build
      - name: Run app
        run: docker compose -f docker-compose-prod.yml up -d
