name: deploy-digital-ocean
on:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: beapengine
    steps:
      - name: Add permissions
        run: chown -R autodeploy:autodeploy /home/autodeploy/actions-runner/_work/term-project-2024-team-3/term-project-2024-team-3/services/ml-service/
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env
        run: |
          echo "POSTGRESQL_URL=${{ secrets.POSTGRESQL_URL }}" > .env
          echo "PG_CRYPTO_KEY=${{ secrets.PG_CRYPTO_KEY }}" >> .env
          cd frontend
          echo "REACT_APP_ROLLBAR_ACCESS_TOKEN=${{ secrets.ROLLBAR_ACCESS_TOKEN }}" > .env
      - name: Build containers
        run: docker compose -f docker-compose-prod.yml build
      - name: Run app
        run: docker compose -f docker-compose-prod.yml up -d
