name: deploy-digital-ocean
on:
    pull_request:
        branches:
          - master
        types: [closed]

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'master' && github.event_name == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build containers     
        run: docker-compose -f docker-compose-prod.yml build
      - name: Run app    
        run: docker-compose -f docker-compose-prod.yml up -d
