name: deploy-digital-ocean
on:
  # workflow_run:
  #   workflows: [frontend, playwright]
  #   branches: [master]
  #   types:
  #     - completed
  pull_request:

jobs:
  build-and-deploy:
    runs-on: beapengine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env
        run: |
          echo "POSTGRESQL_URL=${{ secrets.POSTGRESQL_URL }}" > .env
          echo "PG_CRYPTO_KEY=${{ secrets.PG_CRYPTO_KEY }}" >> .env
          echo "ROLLBAR_ACCESS_TOKEN=${{ secrets.ROLLBAR_ACCESS_TOKEN }}" >> .env
      - name: Build containers
        run: docker compose -f docker-compose-prod.yml build
      - name: Run app
        run: docker compose -f docker-compose-prod.yml up -d
