name: frontend
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "frontend/*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install
      - name: Run lint
        run: |
          cd frontend
          yarn lint
      - name: Build Frontend
        run: |
          cd frontend
          yarn run build
      - name: Run Unit and Integration Tests
        run: |
          cd frontend
          yarn test --ci --json --coverage --testLocationInResults --outputFile=report.json
      - name: Frontend code coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          skip-step: all
          working-directory: ./frontend
          custom-title: Frontend Code Coverage Report
