name: Build and Test
on:
    push:
      branches:
        - development
        - master
    pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install frontend dependencies     
        run: |
            cd frontend
            yarn install
      - name: Frontend Unit and Integration Tests
        run: |
            cd frontend
            yarn run test
            