name: playwright
on:
  push:
    branches:
      - master
      - release/*

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build and run tests
        run: docker-compose -p beapengine-staging -f docker-compose-staging.yml up --build --abort-on-container-exit
